import type { Metadata } from "next";
import "./globals.css";
import { HeaderWrapper } from "@/(app)/_component/ui/HeaderWrapper";
// import { Header } from "./_component";
import { Nunito_Sans } from "next/font/google";
import Footer from "./_component/ui/Footer";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} bg-black text-white antialiased`}
      >
        <HeaderWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
