backend:
  name: github
  repo: Ritesh-Maharjan/Webteck
  branch: main
  auth_type: oauth
  base_url: "https://webteck.ca"
  proxy_url: "/api/auth/login" # Full absolute URL
  site_url: "https://webteck.ca"
  auth_endpoint: "api/auth/login"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}" # Use the title to generate the filename
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
