backend:
  name: github
  repo: Ritesh-Maharjan/Webteck
  branch: main
  auth_type: oauth
  # proxy_url: "http://localhost:3000/api/auth/login"
  # site_url: "http://localhost:3000"
  # site_url: "https://webteck.ca"
  # base_url: "https://webteck.ca"
  # base_url: "http://localhost:3000"
  # auth_endpoint: "api/auth/login"

media_folder: "/public/uploads" # Where images will be stored
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}" # Use the title to generate the filename
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
